[build]
  command = "pnpm install && pnpm run -F './apps/**' -r build"
  publish = "apps/codex/.next"

[build.environment]
  NODE_VERSION = "18.14.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    cache = true
    nextConfigPath = "next.config.js"
    installCommand = "pnpm install"
    buildCommand = "pnpm run build"
    target = "server"
    generateEtags = true
    includeDirs = ["public", "static"]
    excludeDirs = ["node_modules", "tests"]