[build]
  command = "pnpm run build"
  publish = ".next"

[functions]
  directory = "./.netlify/functions"

# [build.environment]
#   NODE_VERSION = "20.12.2"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# [cache]
#   paths = ["node_modules", "apps/**/node_modules", "packages/**/node_modules"]
